### ISSUE TITLE
jupyter-cms in a Conda environment

### ISSUE THREAD

**Issue by stubz01** [jupyter-incubator/contentmanagement#31]
I was having some trouble the other day getting the jupyter-cms module to fire up ...
I seem to be able to get it to run from my console prompt now,
but it doesn't seem to want to go into a Conda's environment, when I try and create one ...

**Comment by parente** [comment]
Please try:

```
conda create -n test-env python=3
source activate test-env
pip install jupyter_cms
jupyter cms install --user --symlink --overwrite
jupyter cms activate
jupyter notebook
```

If it fails, please post the logs. Or please post what you're running and the output from those commands.

Thanks!

**Comment by stubz01** [comment]
Thanx ... This actually occurred to me this morning ...
I guess I'm a bit slow on the up take ...
I think the activation of the conda source and then  the activation of the jupyter cms kinda threw me ...

The 'jupyter cms install --user --symlink --overwrite' line is only required once in the environment, after the pip install ¿
And the activation, may or may not be, invoked when returning to tinker around later ... ¿

Is deactivation of the jupyter cms necessary ?
Ctrl-c twice seems to shut things down ...

Thanx again ...

Cheerz

**Comment by parente** [comment]
> conda create -n test-env python=3

Creates the conda environment.

> source activate test-env

Sets up your shell environment so that pip, python, etc. come from the conda environment you created.

> pip install jupyter_cms

Fetches and installs the Python package.

I should have added `conda install -y jupyter` next because it's needed for the components to install and activate properly.

> jupyter cms install --user --symlink --overwrite

Links the JavaScript components from the Python package into your `~/.jupyter` directory (which is outside the conda environment). This means it will be available even when your conda environment is not active (which is probably not what you want). Jupyter Notebook 4.2 will fix this so it's easier to install into your conda environment.

> jupyter cms activate

Writes a Jupyter configuration file to enable the JavaScript and Python extensions to the notebook. 

> jupyter notebook

Runs Jupyter notebook.

If you quit the terminal and open a new one, the only commands you need to rerun are:

```
source activate test-env
jupyter notebook
```

**Comment by stubz01** [comment]
Cheerz, I think I got it now ...
Just gotta slow down a bit and put all the pieces together, in the right order ...
Sooner or later, I'll remember, to remember, that ...

How does the  -y (Do not ask for confirmation) change things ?
If jupyter/ipython is in the Condas package manger already, when is that meant to be done ?

**Comment by parente** [comment]
The `-y` just skips the prompt for confirmation that you do indeed want to install Jupyter **and** perform whatever operations conda wants to perform (e.g., it will update other libraries along the way if it sees there are newer versions that are compatible.)

**Comment by parente** [comment]
@stubz01 it looks from your last message that you got the extension installed. I'm going to close this, but feel free to open new issues if you hit new problems.
